fix: ci scp migrations

diff --git a/.github/workflows/build-and-deploy.yaml b/.github/workflows/build-and-deploy.yaml
--- a/.github/workflows/build-and-deploy.yaml
+++ b/.github/workflows/build-and-deploy.yaml
@@ -76,9 +76,25 @@ jobs:
           # fingerprint: ${{ secrets.DROPLET_FINGERPRINT }}
           source: "server/db/migrations"
           target: "~/typedash/db/migrations"
-          strip_components: 1
+          strip_components: 3
 
-      - name: Deploy and run migrations on Droplet
+      # UNCOMMENT TO UPDATE SECRETS
+      # - name: Set secrets on Droplet
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #     host: ${{ secrets.DROPLET_HOST }}
+      #     username: ${{ secrets.DROPLET_USERNAME }}
+      #     key: ${{ secrets.DROPLET_KEY }}
+      #     # fingerprint: ${{ secrets.DROPLET_FINGERPRINT }}
+      #     script: |
+      #       mkdir -p ~/typedash/secrets
+      #       echo "${{ secrets.JWT_SECRET }}" > ~/typedash/secrets/jwt_secret
+      #       echo "${{ secrets.POSTGRES_USER }}" > ~/typedash/secrets/postgres_user
+      #       echo "${{ secrets.POSTGRES_PASSWORD }}" > ~/typedash/secrets/postgres_password
+      #       echo "${{ secrets.POSTGRES_DB }}" > ~/typedash/secrets/postgres_db
+      #       chmod 666 ~/typedash/secrets/*
+
+      - name: Deploy on Droplet
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.DROPLET_HOST }}
@@ -86,17 +102,21 @@ jobs:
           key: ${{ secrets.DROPLET_KEY }}
           # fingerprint: ${{ secrets.DROPLET_FINGERPRINT }}
           script: |
-            mkdir -p ~/typedash/secrets
-            echo "${{ secrets.JWT_SECRET }}" > ~/typedash/secrets/jwt_secret
-            echo "${{ secrets.POSTGRES_USER }}" > ~/typedash/secrets/postgres_user
-            echo "${{ secrets.POSTGRES_PASSWORD }}" > ~/typedash/secrets/postgres_password
-            echo "${{ secrets.POSTGRES_DB }}" > ~/typedash/secrets/postgres_db
-            chmod 666 ~/typedash/secrets/*
-
             set -e
             trap 'echo "Error on line $LINENO"; exit 1' ERR
 
             cd ~/typedash && docker compose -f compose.prod.yaml up -d --pull always
 
-            # Run database migrations (sslmode=disable is required for golang-migrate to work)
+      - name: Run migrations on Droplet
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.DROPLET_HOST }}
+          username: ${{ secrets.DROPLET_USERNAME }}
+          key: ${{ secrets.DROPLET_KEY }}
+          # fingerprint: ${{ secrets.DROPLET_FINGERPRINT }}
+          script: |
+            set -e
+            trap 'echo "Error on line $LINENO"; exit 1' ERR
+
+            # sslmode=disable is required for golang-migrate to work
             migrate -path ~/typedash/db/migrations -database "postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}?sslmode=disable" up
